name: Java CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Verify formatting (fails if dirty)
        run: ./gradlew --no-daemon spotlessCheck

      - name: Run tests
        run: ./gradlew --no-daemon test

      - name: Build application
        run: ./gradlew --no-daemon build
